import {StyleSheet} from 'react-native';
import {Colors} from '../../common/styles/color';
import {horizontalScale} from '../../common/styles/styles';

export const styles = StyleSheet.create({
  mainBox: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  headerContainer: {
    backgroundColor: '#8e4ab8',
    height: horizontalScale(80),
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    elevation: horizontalScale(10),
    shadowOpacity: horizontalScale(10),
    shadowRadius: horizontalScale(15),
  },
  headerMain: {
    height: horizontalScale(80),
    width: '65%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerFont: {
    fontSize: horizontalScale(20),
    marginLeft: horizontalScale(15),
    fontWeight: '600',
    color: Colors.white,
  },
  headerIconMain: {
    height: horizontalScale(80),
    width: '35%',
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
  },
  headerIcon: {
    height: horizontalScale(35),
    tintColor: Colors.white,
    width: horizontalScale(35),
  },
  bigfont: {
    fontSize: horizontalScale(22),
    fontWeight: '800',
    marginTop: horizontalScale(20),
    color: '#533668',
  },
  boxConatiner: {
    backgroundColor: 'white',
    height: horizontalScale(150),
    width: '100%',
    marginTop: horizontalScale(15),
    borderRadius: horizontalScale(10),
    elevation: horizontalScale(6),
    shadowOpacity: horizontalScale(20),
    shadowRadius: horizontalScale(10),
  },
  boxFont: {
    fontSize: horizontalScale(17),
    marginLeft: horizontalScale(8),
    fontWeight: '600',
    marginTop: horizontalScale(5),
    color: Colors.fontColor,
  },
  boxIconConatin: {
    height: '65%',
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
    flexDirection: 'row',
  },
  boxIcon: {
    height: horizontalScale(50),
    width: horizontalScale(50),
    marginRight: horizontalScale(20),
    bottom: horizontalScale(30),
    tintColor: Colors.fontColor,
  },
  boxBigFont: {
    fontSize: horizontalScale(50),
    fontWeight: '600',
    marginRight: horizontalScale(20),
    bottom: horizontalScale(27),
    color: Colors.fontColor,
  },
  bigBoxConatin: {
    height: horizontalScale(150),
    marginTop: horizontalScale(30),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  bigBoxTextContain: {
    height: '98%',
    width: '45%',
    flexDirection: 'column',
    backgroundColor: Colors.white,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: horizontalScale(10),
    elevation: horizontalScale(6),
    shadowOpacity: horizontalScale(20),
    shadowRadius: horizontalScale(10),
  },
  bigBoxCon:{
    backgroundColor: 'white',
    height: horizontalScale(150),
    width: '100%',
    marginTop: horizontalScale(15),
    flexDirection: 'row',
    borderRadius: horizontalScale(10),
    elevation: horizontalScale(6),
    shadowOpacity: horizontalScale(20),
    shadowRadius: horizontalScale(10),
  },
  bigBoxSmallText:{
    fontSize: horizontalScale(17),
    marginLeft: horizontalScale(8),
    fontWeight: '600',
    marginTop: horizontalScale(3),
    color: Colors.fontColor,
  },
  bigBoxIconContain:{
    height: '100%',
    width: '35%',
    // backgroundColor: 'pink',
    alignItems: 'flex-end',
    justifyContent: 'flex-end',
    flexDirection: 'row',
  },
  bigBocIcon2:{
    height: horizontalScale(50),
    width: horizontalScale(50),
    marginRight: horizontalScale(10),
    bottom: horizontalScale(10),
    tintColor: Colors.fontColor,
  },
  bigBoxBigText2:{
    fontSize: horizontalScale(50),
    fontWeight: '600',
    marginRight: horizontalScale(20),
    bottom: horizontalScale(5),
    color: Colors.fontColor,
  },
  icon:{
    height: horizontalScale(50),
    width: horizontalScale(50),
  },
  iconText:{
    fontSize: horizontalScale(17),
    fontWeight: '600',
    marginTop: horizontalScale(10),
    color: Colors.fontColor,
  },
  modelConatin:{
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.1)',
  },
  modelMain:{
    flex: 1,
    alignItems: 'flex-end',
  },
  modelMainConatin:{
    backgroundColor: 'white',
    width: '50%',
    padding: horizontalScale(20),
    alignItems: 'center',
    elevation: 5,
    marginTop: horizontalScale(25),
    marginRight: horizontalScale(20),
  },
  modelView:{
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-around',
  },
  modelFont:{
    fontSize: horizontalScale(20),
    fontWeight: '600',
    color: Colors.black,
  },
  modelIcon:{
    height: horizontalScale(35),
    width: horizontalScale(35),
    marginLeft: horizontalScale(15),
  },
  modelViewContain: {
    flexDirection: 'row',
    marginTop: horizontalScale(15),
    width: '100%',
    justifyContent: 'space-around',
  }
});
